export const jalaliSample = [
	{
		id: "jalali-nowruz-day1",
		type: "fixed",
		month: 1,
		day: 1,
		title: { fa: "نوروز", en: "Nowruz" },
		categories: ["national", "cultural"],
		isHoliday: true,
		isOfficialHolidayInIran: true,
	},
	{
		id: "jalali-nowruz-holidays",
		type: "multi-day",
		startMonth: 1,
		startDay: 1,
		endMonth: 1,
		endDay: 4,
		title: { fa: "تعطیلات نوروز", en: "Nowruz Holidays" },
		categories: ["national", "cultural"],
		isHoliday: true,
		isOfficialHolidayInIran: true,
	},
	{
		id: "jalali-teachers-day",
		type: "fixed",
		month: 2,
		day: 12,
		title: { fa: "روز معلم", en: "Teacher's Day" },
		categories: ["national", "memorial"],
		isHoliday: false,
		isOfficialHolidayInIran: false,
	},
];

export const gregorianSample = [
	{
		id: "gregorian-mothers-day",
		type: "relative",
		rule: { base: "month-weekday", month: 5, weekday: 0, occurrence: "second" },
		title: { fa: "روز مادر", en: "Mother's Day" },
		categories: ["international", "cultural"],
		isHoliday: false,
		isOfficialHolidayInIran: false,
	},
	{
		id: "gregorian-christmas",
		type: "fixed",
		month: 12,
		day: 25,
		title: { fa: "کریسمس", en: "Christmas Day" },
		categories: ["international", "religious"],
		isHoliday: true,
		isOfficialHolidayInIran: false,
	},
];

export const loaderSample = [
	{
		id: "fixed-m1d1",
		type: "fixed",
		month: 1,
		day: 1,
		title: { fa: "روز اول", en: "Day One" },
		categories: ["national"],
		isHoliday: true,
		isOfficialHolidayInIran: true,
	},
	{
		id: "fixed-m1d15",
		type: "fixed",
		month: 1,
		day: 15,
		title: { fa: "روز پانزدهم", en: "Day Fifteen" },
		categories: ["cultural"],
		isHoliday: false,
		isOfficialHolidayInIran: false,
	},
	{
		id: "fixed-m6d31",
		type: "fixed",
		month: 6,
		day: 31,
		title: { fa: "روز پایان شهریور", en: "End of Shahrivar" },
		categories: ["national"],
		isHoliday: false,
		isOfficialHolidayInIran: false,
	},
	{
		id: "multi-m1d1-4",
		type: "multi-day",
		startMonth: 1,
		startDay: 1,
		endMonth: 1,
		endDay: 4,
		title: { fa: "هفته نوروز", en: "Nowruz Week" },
		categories: ["national", "cultural"],
		isHoliday: true,
		isOfficialHolidayInIran: true,
	},
	{
		id: "relative-mothers-day",
		type: "relative",
		rule: {
			base: "nth-weekday-of-month",
			month: 5,
			weekday: 0,
			occurrence: "second",
		},
		title: { fa: "روز مادر", en: "Mother's Day" },
		categories: ["cultural"],
		isHoliday: false,
		isOfficialHolidayInIran: false,
	},
];
